port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
tcp-concurrent: true
external-controller: :9090
external-ui: ./ui
geodata-mode: true
global-client-fingerprint: chrome
profile:
  store-selected: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - Mijia Cloud
    - dlg.io.mi.com
  sniff:
    TLS:
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
tun:
  enable: true #false #需要修改为true
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true

dns: #需要修改为true #false
  enable: true
  listen: :1010
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - "[2402:4e00::]"
    - "[2400:3200::1]"
  nameserver:
    - "tls://8.8.4.4#dns"
    - "tls://1.0.0.1#dns"
    - "tls://[2001:4860:4860::8844]#dns"
    - "tls://[2606:4700:4700::1001]#dns"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

experimental:
  ignore-resolve-fail: true
unified-delay: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - lumao1
      - DIRECT

  - name: "lumao1"
    # type: url-test 自动选择最快的线路 type: select 手动选择
    type: url-test
    use:
      - provider1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 50

proxy-providers:
  provider1:
    type: file
    path: /root/lumao/proxy_providers/proxy_1_proxy_1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      expected-status: 204
    override:
      udp: true

rule-providers:
  reject:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: /root/lumao/ruleset/reject.yaml
    interval: 86400

  icloud:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: /root/lumao/ruleset/icloud.yaml
    interval: 86400

  apple:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: /root/lumao/ruleset/apple.yaml
    interval: 86400

  google:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: /root/lumao/ruleset/google.yaml
    interval: 86400

  proxy:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: /root/lumao/ruleset/proxy.yaml
    interval: 86400

  direct:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: /root/lumao/ruleset/direct.yaml
    interval: 86400

  private:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: /root/lumao/ruleset/private.yaml
    interval: 86400

  gfw:
    type: file
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: /root/lumao/ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: file
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: /root/lumao/ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: file
    behavior: ipcidr
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: /root/lumao/ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: file
    behavior: ipcidr
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: /root/lumao/ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: file
    behavior: ipcidr
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: /root/lumao/ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: file
    behavior: classical
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: /root/lumao/ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
